from __future__ import annotations

from typing import Any, Protocol


class ChatModelProvider(Protocol):
    def chat(
        self,
        model: str | None = None,
        *,
        temperature: float | None = None,
        reasoning: bool | str | None = None,
    ) -> Any: ...

    def json_chat(self, model: str | None = None) -> Any: ...

    def count_message_tokens(self, model: str | None, messages: list[Any]) -> int: ...

    def effective_context_window(self, model: str | None = None, *, ttl_seconds: float = 15.0) -> int: ...

    def ollama_context_window(self) -> int | None: ...

    def set_ollama_context_window(self, context_window: int | None) -> int | None: ...

    def loaded_models(self) -> tuple[str, ...]: ...

    def unload_model(self, model: str) -> dict[str, Any]: ...

    def abort_active_requests(self) -> None: ...
